// File generated by FlutterFire CLI.
// This file configures Firebase for the V Astra Create app.
// Replace with your actual Firebase configuration from Firebase Console.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'dart:io' show Platform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) {
      return android;
    }
    if (Platform.isIOS) {
      return ios;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTx1iiUW3cGJrS-NJHm_tKUNjnrV6JcH4',
    appId: '1:110782823215: android: 77f8357842db25183fbfda',
    messagingSenderId: '110782823215',
    projectId: 'v-astra-create',
    storageBucket: 'v-astra-create.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_FIREBASE_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'com.vastra.create',
  );
}
